### ISSUE TITLE
Import time

### ISSUE THREAD

**Issue by Vendelator** [tstenvold/pico-w-mpy-starter#1]
You import time in mail.py and wifi.py. From my understanding it should Be sufficient to do this from main.

Keep up the great work. 👍

**Comment by tstenvold** [comment]
You are correct that it isn't entirely necessary. However, This was done on purpose to allow the reuse of wifi.py without being imported by main as both use the time import. 

Furthermore, it has no impact as once imported, MicroPy keeps track of that and won't re-import it.

**Comment by tstenvold** [comment]
You are correct that it isn't entirely necessary. However, This was done on purpose to allow the reuse of wifi.py without being imported by main as both use the time import.

Furthermore, it has no impact as once imported, MicroPy keeps track of that and won't re-import it.
